const BASE_MASTERY = {
  recentWindow: 10,
  minAccuracy: 0.85,
  maxMedianResponseMs: 9000,
  maxHintRate: 0.45,
  minStreak: 5,
  minFocusAccuracy: 0.8,
};

export const INTEGER_PROGRESSION_THEMES = [
  {
    key: "foundations",
    label: "Foundations",
    levelRange: [1, 10],
    scoreTier: "beginner",
    threshold: 300,
    minAttempts: 10,
    speedBands: [
      { maxMs: 4000, score: 100 },
      { maxMs: 6000, score: 80 },
      { maxMs: 8000, score: 60 },
      { maxMs: Number.POSITIVE_INFINITY, score: 30 },
    ],
  },
  {
    key: "sign_logic",
    label: "Sign Logic",
    levelRange: [11, 20],
    scoreTier: "intermediate",
    threshold: 350,
    minAttempts: 12,
    speedBands: [
      { maxMs: 3000, score: 100 },
      { maxMs: 5000, score: 80 },
      { maxMs: 7000, score: 60 },
      { maxMs: Number.POSITIVE_INFINITY, score: 30 },
    ],
  },
  {
    key: "mixed_flexibility",
    label: "Mixed Flexibility",
    levelRange: [21, 30],
    scoreTier: "mixed",
    threshold: 350,
    minAttempts: 12,
    speedBands: [
      { maxMs: 3000, score: 100 },
      { maxMs: 5000, score: 80 },
      { maxMs: 7000, score: 60 },
      { maxMs: Number.POSITIVE_INFINITY, score: 30 },
    ],
  },
  {
    key: "fluency_mastery",
    label: "Fluency and Mastery",
    levelRange: [31, 40],
    scoreTier: "advanced",
    threshold: 400,
    minAttempts: 15,
    speedBands: [
      { maxMs: 2500, score: 100 },
      { maxMs: 4000, score: 80 },
      { maxMs: 6000, score: 60 },
      { maxMs: Number.POSITIVE_INFINITY, score: 30 },
    ],
  },
];

export const INTEGER_PROGRESSION_RULES = {
  hardFail: {
    minAccuracy: 0.8,
    minFocusAccuracy: 0.8,
    minStreak: 5,
    maxHintRate: 0.2,
  },
  struggling: {
    minAccuracy: 0.7,
    maxHintRate: 0.3,
  },
  scoring: {
    accuracyBands: [
      { min: 0.9, score: 100 },
      { min: 0.85, score: 85 },
      { min: 0.8, score: 70 },
    ],
    streakBands: [
      { min: 10, score: 100 },
      { min: 7, score: 80 },
      { min: 5, score: 60 },
    ],
    hintBands: [
      { max: 0, score: 100 },
      { max: 0.1, score: 85 },
      { max: 0.2, score: 70 },
    ],
    focusBands: [
      { min: 0.9, score: 100 },
      { min: 0.85, score: 85 },
      { min: 0.8, score: 70 },
    ],
  },
  focusFallbackMinAttempts: 4,
  weakSkillTagMinAttempts: 3,
  weakSkillTagMaxAccuracy: 0.74,
  weakSkillTagMaxHintRate: 0.35,
  closeThresholdBuffer: 35,
  displayBlockedReasons: 2,
  evaluationWindowByTier: {
    beginner: 10,
    intermediate: 12,
    mixed: 12,
    advanced: 15,
  },
};

const HEAVY_SUPPORT = {
  answerMode: "multiple_choice",
  choiceCount: 2,
  showCounters: true,
  showNumberLine: true,
  numberLineStyle: "static",
  showHintButton: true,
  showStrategyPrompt: true,
  colorSigns: true,
  showOperationWords: true,
  rewriteSubtractNegative: true,
  highlightAbsoluteValue: true,
  stepByStep: true,
  reducedDistractors: true,
  untimed: true,
  allowRetry: true,
  confidenceCheck: false,
  instantExplanation: true,
  repeatedPatterning: true,
  timedPressure: false,
};

const GUIDED_SUPPORT = {
  ...HEAVY_SUPPORT,
  choiceCount: 3,
  numberLineStyle: "animated",
  reducedDistractors: false,
  confidenceCheck: true,
};

const LIGHT_SUPPORT = {
  ...GUIDED_SUPPORT,
  choiceCount: 4,
  showCounters: false,
  showStrategyPrompt: false,
  showOperationWords: false,
  highlightAbsoluteValue: false,
  stepByStep: false,
  repeatedPatterning: false,
};

const FLUENCY_SUPPORT = {
  ...LIGHT_SUPPORT,
  answerMode: "open_response",
  showNumberLine: false,
  showHintButton: false,
  rewriteSubtractNegative: false,
  untimed: false,
  allowRetry: false,
  confidenceCheck: false,
  instantExplanation: false,
  timedPressure: true,
};

function createLevel({
  id,
  name,
  description,
  maxAbs,
  allowedOperations,
  problemTypes,
  skillTags,
  scaffolds,
  timeTargetSeconds,
  questionCountForEvaluation = 10,
  distractorProfile = "standard",
  masteryRules = {},
}) {
  return {
    id,
    name,
    description,
    numberRange: { min: 0, max: maxAbs },
    allowedOperations,
    problemTypes,
    skillTags,
    scaffolds,
    masteryRules: {
      ...BASE_MASTERY,
      ...masteryRules,
    },
    timeTargetSeconds,
    questionCountForEvaluation,
    distractorProfile,
  };
}

export const INTEGER_SKILL_TAGS = [
  "positive_addition",
  "positive_subtraction",
  "subtraction_to_zero",
  "subtraction_to_negative",
  "negative_plus_negative",
  "positive_plus_negative",
  "negative_plus_positive",
  "subtract_negative",
  "negative_minus_positive",
  "negative_minus_negative",
  "crosses_zero",
  "same_sign_addition",
  "different_sign_addition",
  "same_sign_subtraction_pattern",
  "mixed_integer_operations",
  "small_numbers",
  "medium_numbers",
  "large_numbers",
];

export const INTEGER_LEVELS = [
  createLevel({
    id: 1,
    name: "Level 1 · Tiny Positive Addition",
    description: "Start with tiny positive addition facts like 2 + 1.",
    maxAbs: 5,
    allowedOperations: ["+"],
    problemTypes: ["positive_addition"],
    skillTags: ["positive_addition", "small_numbers"],
    scaffolds: HEAVY_SUPPORT,
    timeTargetSeconds: 14,
    distractorProfile: "gentle",
    masteryRules: { minAccuracy: 0.8, maxMedianResponseMs: 12000, minStreak: 3 },
  }),
  createLevel({
    id: 2,
    name: "Level 2 · Positive Addition To 10",
    description: "Positive addition grows to totals within 10.",
    maxAbs: 10,
    allowedOperations: ["+"],
    problemTypes: ["positive_addition"],
    skillTags: ["positive_addition", "small_numbers"],
    scaffolds: HEAVY_SUPPORT,
    timeTargetSeconds: 13,
    distractorProfile: "gentle",
  }),
  createLevel({
    id: 3,
    name: "Level 3 · Positive Addition To 20",
    description: "Stretch positive addition with slightly bigger numbers.",
    maxAbs: 20,
    allowedOperations: ["+"],
    problemTypes: ["positive_addition"],
    skillTags: ["positive_addition", "medium_numbers"],
    scaffolds: { ...HEAVY_SUPPORT, choiceCount: 3 },
    timeTargetSeconds: 12,
  }),
  createLevel({
    id: 4,
    name: "Level 4 · Positive Subtraction Within 5",
    description: "Subtract positives when the first number is still bigger.",
    maxAbs: 5,
    allowedOperations: ["-"],
    problemTypes: ["positive_subtraction_nonnegative"],
    skillTags: ["positive_subtraction", "small_numbers"],
    scaffolds: HEAVY_SUPPORT,
    timeTargetSeconds: 14,
    distractorProfile: "gentle",
  }),
  createLevel({
    id: 5,
    name: "Level 5 · Positive Subtraction Within 10",
    description: "Subtraction facts within 10 with support still on.",
    maxAbs: 10,
    allowedOperations: ["-"],
    problemTypes: ["positive_subtraction_nonnegative"],
    skillTags: ["positive_subtraction", "small_numbers"],
    scaffolds: HEAVY_SUPPORT,
    timeTargetSeconds: 13,
  }),
  createLevel({
    id: 6,
    name: "Level 6 · Subtraction To Zero",
    description: "Include subtraction facts that can end at exactly zero.",
    maxAbs: 10,
    allowedOperations: ["-"],
    problemTypes: ["subtraction_to_zero"],
    skillTags: ["positive_subtraction", "subtraction_to_zero", "small_numbers"],
    scaffolds: HEAVY_SUPPORT,
    timeTargetSeconds: 13,
  }),
  createLevel({
    id: 7,
    name: "Level 7 · Positive Subtraction Below Zero",
    description: "Let the first number be smaller so the answer can turn negative.",
    maxAbs: 10,
    allowedOperations: ["-"],
    problemTypes: ["positive_subtraction_negative"],
    skillTags: ["subtraction_to_negative", "crosses_zero", "small_numbers"],
    scaffolds: GUIDED_SUPPORT,
    timeTargetSeconds: 13,
  }),
  createLevel({
    id: 8,
    name: "Level 8 · Mixed Positive Add/Sub Within 10",
    description: "Mix positive addition and subtraction without changing supports too sharply.",
    maxAbs: 10,
    allowedOperations: ["+", "-"],
    problemTypes: ["positive_addition", "positive_subtraction_nonnegative", "subtraction_to_zero"],
    skillTags: ["positive_addition", "positive_subtraction", "small_numbers"],
    scaffolds: GUIDED_SUPPORT,
    timeTargetSeconds: 12,
  }),
  createLevel({
    id: 9,
    name: "Level 9 · Mixed Positive Add/Sub Across Zero",
    description: "Positive-only equations now include subtraction that can move below zero.",
    maxAbs: 12,
    allowedOperations: ["+", "-"],
    problemTypes: ["positive_addition", "positive_subtraction_negative", "subtraction_to_zero"],
    skillTags: ["positive_addition", "subtraction_to_negative", "crosses_zero", "small_numbers"],
    scaffolds: GUIDED_SUPPORT,
    timeTargetSeconds: 12,
  }),
  createLevel({
    id: 10,
    name: "Level 10 · Negative Plus Negative",
    description: "Start adding two negative numbers with small magnitudes.",
    maxAbs: 5,
    allowedOperations: ["+"],
    problemTypes: ["negative_plus_negative"],
    skillTags: ["negative_plus_negative", "same_sign_addition", "small_numbers"],
    scaffolds: GUIDED_SUPPORT,
    timeTargetSeconds: 12,
  }),
  createLevel({
    id: 11,
    name: "Level 11 · Bigger Negative Plus Negative",
    description: "Keep same-sign negative addition but widen the range.",
    maxAbs: 10,
    allowedOperations: ["+"],
    problemTypes: ["negative_plus_negative"],
    skillTags: ["negative_plus_negative", "same_sign_addition", "small_numbers"],
    scaffolds: GUIDED_SUPPORT,
    timeTargetSeconds: 11,
  }),
  createLevel({
    id: 12,
    name: "Level 12 · Positive Plus Negative, Still Positive",
    description: "Use opposite signs while keeping the answer nonnegative.",
    maxAbs: 10,
    allowedOperations: ["+"],
    problemTypes: ["positive_plus_negative_positive"],
    skillTags: ["positive_plus_negative", "different_sign_addition", "small_numbers"],
    scaffolds: GUIDED_SUPPORT,
    timeTargetSeconds: 11,
  }),
  createLevel({
    id: 13,
    name: "Level 13 · Positive Plus Negative To Zero",
    description: "Allow opposite-sign addition that can land on zero.",
    maxAbs: 10,
    allowedOperations: ["+"],
    problemTypes: ["positive_plus_negative_zero_or_positive"],
    skillTags: ["positive_plus_negative", "different_sign_addition", "crosses_zero", "small_numbers"],
    scaffolds: GUIDED_SUPPORT,
    timeTargetSeconds: 11,
  }),
  createLevel({
    id: 14,
    name: "Level 14 · Positive Plus Negative Any Answer",
    description: "Opposite-sign addition now may produce positive or negative answers.",
    maxAbs: 10,
    allowedOperations: ["+"],
    problemTypes: ["positive_plus_negative_any", "negative_plus_positive_any"],
    skillTags: ["positive_plus_negative", "negative_plus_positive", "different_sign_addition", "crosses_zero", "small_numbers"],
    scaffolds: { ...GUIDED_SUPPORT, choiceCount: 4 },
    timeTargetSeconds: 10,
  }),
  createLevel({
    id: 15,
    name: "Level 15 · Same-Sign Addition Mix",
    description: "Mix positive and negative addition while same-sign patterns stay visible.",
    maxAbs: 12,
    allowedOperations: ["+"],
    problemTypes: ["positive_addition", "negative_plus_negative"],
    skillTags: ["same_sign_addition", "medium_numbers"],
    scaffolds: LIGHT_SUPPORT,
    timeTargetSeconds: 10,
  }),
  createLevel({
    id: 16,
    name: "Level 16 · Opposite-Sign Addition Mix",
    description: "Practice opposite-sign addition with less prompting.",
    maxAbs: 12,
    allowedOperations: ["+"],
    problemTypes: ["positive_plus_negative_any", "negative_plus_positive_any"],
    skillTags: ["different_sign_addition", "crosses_zero", "medium_numbers"],
    scaffolds: LIGHT_SUPPORT,
    timeTargetSeconds: 10,
  }),
  createLevel({
    id: 17,
    name: "Level 17 · Subtracting A Negative, Tiny",
    description: "Begin rewriting subtraction of negatives as adding the opposite.",
    maxAbs: 5,
    allowedOperations: ["-"],
    problemTypes: ["subtract_negative"],
    skillTags: ["subtract_negative", "small_numbers"],
    scaffolds: { ...GUIDED_SUPPORT, rewriteSubtractNegative: true, showCounters: false },
    timeTargetSeconds: 11,
  }),
  createLevel({
    id: 18,
    name: "Level 18 · Subtracting A Negative To 10",
    description: "Subtracting negatives gets bigger but still guided.",
    maxAbs: 10,
    allowedOperations: ["-"],
    problemTypes: ["subtract_negative"],
    skillTags: ["subtract_negative", "medium_numbers"],
    scaffolds: LIGHT_SUPPORT,
    timeTargetSeconds: 10,
  }),
  createLevel({
    id: 19,
    name: "Level 19 · Negative Minus Positive",
    description: "Now subtract a positive from a negative number.",
    maxAbs: 10,
    allowedOperations: ["-"],
    problemTypes: ["negative_minus_positive"],
    skillTags: ["negative_minus_positive", "crosses_zero", "medium_numbers"],
    scaffolds: LIGHT_SUPPORT,
    timeTargetSeconds: 10,
  }),
  createLevel({
    id: 20,
    name: "Level 20 · Negative Minus Negative",
    description: "Negative subtraction patterns now mix in where the answer can go either direction.",
    maxAbs: 10,
    allowedOperations: ["-"],
    problemTypes: ["negative_minus_negative"],
    skillTags: ["negative_minus_negative", "same_sign_subtraction_pattern", "crosses_zero", "medium_numbers"],
    scaffolds: LIGHT_SUPPORT,
    timeTargetSeconds: 10,
  }),
  createLevel({
    id: 21,
    name: "Level 21 · Mixed Integer Operations Within 10",
    description: "Bring the core integer patterns together with light supports.",
    maxAbs: 10,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_small"],
    skillTags: ["mixed_integer_operations", "small_numbers"],
    scaffolds: LIGHT_SUPPORT,
    timeTargetSeconds: 10,
  }),
  createLevel({
    id: 22,
    name: "Level 22 · Mixed Integer Operations Within 12",
    description: "Slightly larger numbers with the same core patterns.",
    maxAbs: 12,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_small"],
    skillTags: ["mixed_integer_operations", "medium_numbers"],
    scaffolds: LIGHT_SUPPORT,
    timeTargetSeconds: 9,
  }),
  createLevel({
    id: 23,
    name: "Level 23 · Mixed Integer Operations Open Response",
    description: "Shift out of multiple choice while numbers stay moderate.",
    maxAbs: 12,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_small"],
    skillTags: ["mixed_integer_operations", "medium_numbers"],
    scaffolds: { ...LIGHT_SUPPORT, answerMode: "open_response", allowRetry: true },
    timeTargetSeconds: 10,
    masteryRules: { maxHintRate: 0.3, minAccuracy: 0.85 },
  }),
  createLevel({
    id: 24,
    name: "Level 24 · Cross-Zero Clinic",
    description: "Focus on problems that cross zero in either direction.",
    maxAbs: 15,
    allowedOperations: ["+", "-"],
    problemTypes: ["crosses_zero_mix"],
    skillTags: ["crosses_zero", "mixed_integer_operations", "medium_numbers"],
    scaffolds: { ...LIGHT_SUPPORT, showNumberLine: true, showHintButton: true },
    timeTargetSeconds: 9,
  }),
  createLevel({
    id: 25,
    name: "Level 25 · Larger Absolute Value Second",
    description: "Train the cases where the larger absolute value comes second.",
    maxAbs: 15,
    allowedOperations: ["+", "-"],
    problemTypes: ["larger_abs_second_mix"],
    skillTags: ["different_sign_addition", "subtraction_to_negative", "medium_numbers"],
    scaffolds: { ...LIGHT_SUPPORT, highlightAbsoluteValue: true },
    timeTargetSeconds: 9,
  }),
  createLevel({
    id: 26,
    name: "Level 26 · Subtract Negative To 20",
    description: "Subtracting negatives becomes more fluent and less supported.",
    maxAbs: 20,
    allowedOperations: ["-"],
    problemTypes: ["subtract_negative"],
    skillTags: ["subtract_negative", "medium_numbers"],
    scaffolds: { ...LIGHT_SUPPORT, answerMode: "open_response", allowRetry: true },
    timeTargetSeconds: 8,
  }),
  createLevel({
    id: 27,
    name: "Level 27 · Negative Minus Positive To 20",
    description: "Grow negative-minus-positive fluency with bigger magnitudes.",
    maxAbs: 20,
    allowedOperations: ["-"],
    problemTypes: ["negative_minus_positive"],
    skillTags: ["negative_minus_positive", "medium_numbers"],
    scaffolds: { ...LIGHT_SUPPORT, answerMode: "open_response", allowRetry: true },
    timeTargetSeconds: 8,
  }),
  createLevel({
    id: 28,
    name: "Level 28 · Mixed Integer Operations To 20",
    description: "Core mixed integer work reaches 20 with reduced support.",
    maxAbs: 20,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_medium"],
    skillTags: ["mixed_integer_operations", "medium_numbers"],
    scaffolds: { ...LIGHT_SUPPORT, answerMode: "open_response", allowRetry: true, showHintButton: true },
    timeTargetSeconds: 8,
  }),
  createLevel({
    id: 29,
    name: "Level 29 · Mixed To 20 With Timer",
    description: "Keep the same math, but begin adding gentle time pressure.",
    maxAbs: 20,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_medium"],
    skillTags: ["mixed_integer_operations", "medium_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 18, answerMode: "open_response" },
    timeTargetSeconds: 7,
  }),
  createLevel({
    id: 30,
    name: "Level 30 · Mixed Integer Operations To 30",
    description: "Push magnitudes up while keeping the operation mix stable.",
    maxAbs: 30,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_medium"],
    skillTags: ["mixed_integer_operations", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 16 },
    timeTargetSeconds: 7,
  }),
  createLevel({
    id: 31,
    name: "Level 31 · Larger Absolute Value Hides The Sign",
    description: "Challenge opposite-sign thinking when the larger absolute value moves around.",
    maxAbs: 30,
    allowedOperations: ["+", "-"],
    problemTypes: ["larger_abs_second_mix", "crosses_zero_mix"],
    skillTags: ["different_sign_addition", "crosses_zero", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 16 },
    timeTargetSeconds: 7,
  }),
  createLevel({
    id: 32,
    name: "Level 32 · Mixed Integer Operations To 40",
    description: "Advance toward fluent mental strategy with fewer obvious counting moves.",
    maxAbs: 40,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_large"],
    skillTags: ["mixed_integer_operations", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 15 },
    timeTargetSeconds: 6,
  }),
  createLevel({
    id: 33,
    name: "Level 33 · Mixed Integer Operations To 50",
    description: "Keep the mixed work but push into stronger magnitude fluency.",
    maxAbs: 50,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_large"],
    skillTags: ["mixed_integer_operations", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 15 },
    timeTargetSeconds: 6,
  }),
  createLevel({
    id: 34,
    name: "Level 34 · Advanced Subtract Negative",
    description: "Subtracting negatives now belongs inside larger mixed work.",
    maxAbs: 50,
    allowedOperations: ["-"],
    problemTypes: ["subtract_negative", "negative_minus_negative"],
    skillTags: ["subtract_negative", "negative_minus_negative", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 14 },
    timeTargetSeconds: 6,
  }),
  createLevel({
    id: 35,
    name: "Level 35 · Advanced Cross-Zero Fluency",
    description: "Fast mixed equations that change sign in less obvious ways.",
    maxAbs: 50,
    allowedOperations: ["+", "-"],
    problemTypes: ["crosses_zero_mix", "mixed_core_large"],
    skillTags: ["crosses_zero", "mixed_integer_operations", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 13 },
    timeTargetSeconds: 6,
  }),
  createLevel({
    id: 36,
    name: "Level 36 · Endurance Mix To 50",
    description: "Sustain accurate mixed integer work with strong response consistency.",
    maxAbs: 50,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_large"],
    skillTags: ["mixed_integer_operations", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 13 },
    timeTargetSeconds: 5,
  }),
  createLevel({
    id: 37,
    name: "Level 37 · Fluency Builder",
    description: "Less hinting, tighter time, stronger distractors when multiple choice returns.",
    maxAbs: 50,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_core_large", "subtract_negative"],
    skillTags: ["mixed_integer_operations", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 12 },
    timeTargetSeconds: 5,
    distractorProfile: "tight",
  }),
  createLevel({
    id: 38,
    name: "Level 38 · Challenge Mix",
    description: "Minimal support and a wider mix of sign patterns.",
    maxAbs: 50,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_all_patterns"],
    skillTags: ["mixed_integer_operations", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 12 },
    timeTargetSeconds: 5,
    distractorProfile: "tight",
  }),
  createLevel({
    id: 39,
    name: "Level 39 · Advanced Mental Strategy",
    description: "Fast mixed integer work where mental strategy matters more than counting.",
    maxAbs: 60,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_all_patterns"],
    skillTags: ["mixed_integer_operations", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 11 },
    timeTargetSeconds: 5,
    distractorProfile: "tight",
    masteryRules: { maxMedianResponseMs: 5500, minAccuracy: 0.88, maxHintRate: 0.1 },
  }),
  createLevel({
    id: 40,
    name: "Level 40 · Integer Fluency Summit",
    description: "Full mixed integer fluency, including cases like (-19) - (-37).",
    maxAbs: 60,
    allowedOperations: ["+", "-"],
    problemTypes: ["mixed_all_patterns", "advanced_subtract_negative"],
    skillTags: ["mixed_integer_operations", "subtract_negative", "large_numbers"],
    scaffolds: { ...FLUENCY_SUPPORT, timerSeconds: 10 },
    timeTargetSeconds: 4,
    distractorProfile: "tight",
    masteryRules: { maxMedianResponseMs: 5000, minAccuracy: 0.9, maxHintRate: 0.05, minStreak: 6, minFocusAccuracy: 0.88 },
  }),
].map((level, index, array) => ({
  ...level,
  nextLevelId: array[index + 1]?.id ?? null,
  fallbackLevelId: array[Math.max(0, index - 1)]?.id ?? level.id,
}));

export const INTEGER_LEVEL_MAP = Object.fromEntries(INTEGER_LEVELS.map((level) => [level.id, level]));

export const INTEGER_MODE_PRESETS = {
  adaptive: {
    slug: "adaptive",
    label: "Adaptive Practice",
    description: "Quietly adjusts support and challenge based on recent performance.",
  },
  progression: {
    slug: "progression",
    label: "Level Progression",
    description: "Move through the full integer ladder one careful step at a time.",
  },
  assignment: {
    slug: "assignment",
    label: "Teacher Assignment",
    description: "Lock a level range, focus skill, and scaffold plan for a specific goal.",
  },
  challenge: {
    slug: "challenge",
    label: "Challenge / Fluency",
    description: "Minimal support and tighter timing for automaticity work.",
  },
};

export const DEFAULT_ASSIGNMENT = {
  startLevelId: 1,
  endLevelId: 10,
  focusSkillTag: "mixed_integer_operations",
  forceScaffolds: false,
  questionCount: 12,
  masteryTarget: 0.85,
  timed: false,
  allowAdaptiveSupport: true,
};

export function getLevelById(levelId) {
  return INTEGER_LEVEL_MAP[Number(levelId)] || INTEGER_LEVELS[0];
}

export function listNearbyLevels(levelId, distance = 3) {
  const index = INTEGER_LEVELS.findIndex((level) => level.id === Number(levelId));
  if (index < 0) return INTEGER_LEVELS.slice(0, distance * 2 + 1);
  return INTEGER_LEVELS.slice(Math.max(0, index - distance), Math.min(INTEGER_LEVELS.length, index + distance + 1));
}

export function getProgressionTheme(levelId) {
  const numericLevel = Number(levelId) || 1;
  return (
    INTEGER_PROGRESSION_THEMES.find(
      (theme) => numericLevel >= theme.levelRange[0] && numericLevel <= theme.levelRange[1]
    ) || INTEGER_PROGRESSION_THEMES[0]
  );
}
